### ISSUE TITLE
Seems the bits cannot be built in IntelliJ IDEA 15

### ISSUE THREAD

**Issue by xiaoyongzhu** [Microsoft/Azure-Toolkit-for-IntelliJ#1]
in Windows environment building this project will be failed in IntelliJ 15.

**Comment by BeatriceOltean** [comment]
Thank you. This is taken care right now. There are some breaking changes impacting plugins in the IntelliJ IDEA 15. 
Cheers, 
- Beatrice

**Comment by lenala** [comment]
This is fixed.
